spring.application.name=addcountry
spring.datasource.url=jdbc:mysql://localhost:3306/ormlearn4
spring.datasource.username=root
spring.datasource.password=4#4#4#Ta

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
