spring.application.name=country-service
server.port=8080

spring.datasource.url=jdbc:mysql://localhost:3306/ormlearn2
spring.datasource.username=root
spring.datasource.password=4#4#4#Ta

spring.jpa.hibernate.ddl-auto=validate
spring.jpa.show-sql=true

